# Site settings
title: Mobin Arablou's Personal Webpage
description: My background, present and future plans
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://Mobinlion.github.io" # 

# User settings
username: Mobin Arablou
user_description: Programmer, Web Developer, Ethical Hacker, Arduino hobbyist...
user_title: Software Engineer
email: Mobin@hust.edu.cn
twitter_username: MobinArablou
github_username:  Mobinlion

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
